argo-cd:
  global:
    # Configure the domain for Argo CD. This needs to be overridden with the correct domain by the user of the add-on.
    domain: argo-cd.example.com

  configs:
    cm:
      # Disable the admin user.
      admin.enabled: "false"
      # Define the URL for the Argo CD server.
      url: https://argo-cd.example.com
    params:
      # Activate insecure mode because we terminate the SSL connection at the Traefik Ingress Controller by default.
      server.insecure: "true"

  applicationSet:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi

  controller:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        memory: 1024Mi

  notifications:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi

  repoServer:
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        memory: 1024Mi

  redis:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 512Mi

  server:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hostname: argo-cd.example.com
      extraHosts:
      - name: argo-cd.cluster-name.example.com
        path:  /
      extraTls:
      - hosts:
        - argo-cd.example.com
        - argo-cd.cluster-name.example.com
        secretName: argo-cd-ingress-tls

# ------- #

schtack:
  additionalLabels: {}
  grafanaDashboards: false
