# TODO Enable NetworkPolicies and add custom ones if necessary (such as by the Traefik reverse proxy)
# TODO Add resources definitions

argo-cd:
  configs:
    cm:
      # disable the admin user.
      admin.enabled: "false"
      # Change the tracking method to annotation to allow sourcing Application and ApplicationSet resources from 
      # any namespace.
      application.resourceTrackingMethod: "annotation"
      # Enable the health status for Application resources to allow an App of Apps pattern.
      resource.customizations: |
        argoproj.io/Application: # https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#argocd-app
          health.lua: |
            hs = {}
            hs.status = "Progressing"
            hs.message = ""
            if obj.status ~= nil then
              if obj.status.health ~= nil then
                hs.status = obj.status.health.status
                if obj.status.health.message ~= nil then
                  hs.message = obj.status.health.message
                end
              end
            end
            return hs
        networking.k8s.io/Ingress: # https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-application-stuck-in-progressing-state
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
    params:
      # Allow Argo CD to source ApplicationSet and Application resources from the cluster-apps-* namespaces.
      applicationsetcontroller.namespaces: "cluster-apps-*"
      application.namespaces: "cluster-apps-*"
      # Disable the SCM providers to prevent secret exfiltration when using ApplicationSets in any namespace.
      # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/#scm-providers-secrets-consideration
      applicationsetcontroller.enable.scm.providers: "false"
  dex:
    enabled: false

schtack:
  grafanaDashboards: false
